import Link from "next/link";

import type { Experience, WorkExperience } from "@/api/experience/experience";
import { getExperience } from "@/api/experience/getExperience";
import { getProfile, profileImageUrl } from "@/api/profile/getProfile";
import { getProjects } from "@/api/projects/getProjects";

export const dynamic = "force-dynamic";

const EMPTY_EXPERIENCE: Experience = { id: "", user_id: "" };

function Section({ children, id, label, title }: Readonly<{ children: React.ReactNode; id: string; label: string; title: string }>) {
  return <section className="scroll-mt-8 border-t border-stone-300 py-14 sm:py-20" id={id}><p className="text-xs font-bold uppercase tracking-[0.22em] text-sky-800">{label}</p><h2 className="mt-3 font-serif text-3xl font-semibold tracking-tight text-stone-950 sm:text-4xl">{title}</h2><div className="mt-8">{children}</div></section>;
}

function DetailList({ items }: Readonly<{ items?: string[] | null }>) {
  if (!items?.length) return null;
  return <ul className="grid gap-3 text-stone-700">{items.map((item, index) => <li className="flex gap-3" key={`${item}-${index}`}><span aria-hidden className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-sky-700" />{item}</li>)}</ul>;
}

function WorkCard({ item }: Readonly<{ item: WorkExperience }>) {
  return <article className="grid gap-5 border-l-2 border-stone-300 py-1 pl-6 sm:grid-cols-[minmax(0,1fr)_11rem] sm:gap-8"><div><h3 className="text-xl font-semibold tracking-tight text-stone-950">{item.position}</h3><p className="mt-1 font-medium text-sky-800">{item.company_name}</p>{item.company_description ? <p className="mt-4 leading-7 text-stone-700">{item.company_description}</p> : null}{item.achievements?.length ? <div className="mt-5"><p className="text-sm font-semibold text-stone-900">Key achievements</p><div className="mt-3"><DetailList items={item.achievements} /></div></div> : null}</div><div className="text-sm leading-6 text-stone-500 sm:text-right">{item.start_date || item.end_date ? <p>{[item.start_date, item.end_date].filter(Boolean).join(" — ")}</p> : null}{item.location ? <p>{item.location}</p> : null}{item.Type ? <p>{item.Type}</p> : null}</div></article>;
}

export default async function Home() {
  const [loadedExperience, profile, projects] = await Promise.all([getExperience(), getProfile(), getProjects()]);
  const experience = loadedExperience ?? EMPTY_EXPERIENCE;
  const contact = experience.contact_information;
  const fullName = [contact?.first_name, contact?.last_name].filter(Boolean).join(" ");
  const imageUrl = profileImageUrl(profile?.photo_filename);
  const contactLinks = [
    contact?.email ? { href: `mailto:${contact.email}`, label: "Email" } : null,
    contact?.linkedin ? { href: contact.linkedin, label: "LinkedIn" } : null,
    profile?.github_url ? { href: profile.github_url, label: "GitHub" } : null,
  ].filter(Boolean) as { href: string; label: string }[];

  return <main className="min-h-screen bg-[#f8f7f3] text-stone-900"><div className="mx-auto max-w-6xl px-6 sm:px-10"><header className="flex items-center justify-between gap-6 border-b border-stone-300 py-6"><Link aria-label="Back to top" className="flex items-center gap-3" href="#top"><span className="grid h-8 w-8 place-items-center rounded-full bg-stone-950 font-serif text-sm font-semibold text-white">VP</span><span className="text-sm font-semibold tracking-wide text-stone-700">Portfolio</span></Link><nav aria-label="Main navigation" className="hidden items-center gap-5 text-sm text-stone-600 sm:flex"><a className="transition hover:text-stone-950" href="#experience">Experience</a>{projects.length ? <a className="transition hover:text-stone-950" href="#projects">Projects</a> : null}{experience.skills?.length ? <a className="transition hover:text-stone-950" href="#skills">Skills</a> : null}<a className="transition hover:text-stone-950" href="#contact">Contact</a></nav></header>
    <section className="grid gap-12 py-16 sm:grid-cols-[minmax(0,1.35fr)_minmax(15rem,.65fr)] sm:items-start sm:py-20" id="top"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-sky-800">Independent software engineer</p><h1 className="mt-5 font-serif text-5xl font-semibold leading-[0.95] tracking-tight text-stone-950 sm:text-7xl">{fullName || experience.title}</h1>{experience.title ? <p className="mt-6 text-xl leading-8 text-stone-700 sm:text-2xl">{experience.title}</p> : null}{experience.professional_summary ? <p className="mt-6 max-w-2xl text-base leading-8 text-stone-600 sm:text-lg">{experience.professional_summary}</p> : null}<div className="mt-8 flex flex-wrap gap-3">{profile?.availability ? <span className="rounded-full border border-sky-800/30 bg-sky-50 px-4 py-2 text-sm font-medium text-sky-950">{profile.availability}</span> : null}{contactLinks.map((link) => <a className="rounded-full border border-stone-400 px-4 py-2 text-sm font-medium transition hover:border-stone-950 hover:bg-stone-950 hover:text-white" href={link.href} key={link.label} rel="noreferrer" target="_blank">{link.label}</a>)}</div></div><div className="justify-self-start sm:justify-self-end">{imageUrl ? <img alt={`Portrait of ${fullName || "portfolio owner"}`} className="aspect-[4/5] w-56 object-cover grayscale-[15%] shadow-[12px_12px_0_0_#bae6fd] sm:w-72" src={imageUrl} /> : <div aria-label="Portrait placeholder" className="grid aspect-[4/5] w-56 place-items-end bg-stone-900 p-6 text-right font-serif text-5xl text-stone-100 shadow-[12px_12px_0_0_#bae6fd] sm:w-72">{fullName.split(" ").map((name) => name[0]).join("") || "P"}</div>}<p className="mt-5 max-w-72 border-l-2 border-sky-700 pl-4 text-sm leading-6 text-stone-600">Designing reliable products, systems and delivery processes.</p></div></section>
    {experience.work_experience?.length ? <Section id="experience" label="01 / career" title="Experience"><div className="grid gap-10">{experience.work_experience.map((item, index) => <WorkCard item={item} key={`${item.company_name}-${index}`} />)}</div></Section> : null}
    {projects.length ? <Section id="projects" label="02 / selected work" title="Projects"><div className="grid gap-5 md:grid-cols-2">{projects.map((project) => <article className="group flex min-h-64 flex-col border border-stone-300 bg-white p-6 transition hover:-translate-y-1 hover:border-stone-950" key={project.id}><p className="text-xs font-bold uppercase tracking-[0.16em] text-sky-800">{project.featured ? "Featured project" : "Project"}</p><h3 className="mt-4 font-serif text-2xl font-semibold text-stone-950">{project.title}</h3><p className="mt-3 leading-7 text-stone-600">{project.description}</p>{project.stack?.length ? <div className="mt-5 flex flex-wrap gap-2">{project.stack.map((item) => <span className="text-xs font-medium text-stone-500" key={item}>{item}</span>)}</div> : null}<div className="mt-auto flex gap-4 pt-7 text-sm font-semibold text-sky-800"><a href={project.url} rel="noreferrer" target="_blank">View project ↗</a>{project.repository_url ? <a href={project.repository_url} rel="noreferrer" target="_blank">Source ↗</a> : null}</div></article>)}</div></Section> : null}
    {experience.skills?.length ? <Section id="skills" label="03 / toolkit" title="Skills"><div className="flex flex-wrap gap-2">{experience.skills.map((skill, index) => <span className="border border-stone-300 bg-white px-3 py-1.5 text-sm font-medium text-stone-700" key={`${skill}-${index}`}>{skill}</span>)}</div></Section> : null}
    {experience.education?.length || experience.certifications?.length || experience.publications?.length ? <section className="grid gap-10 border-t border-stone-300 py-14 sm:grid-cols-3 sm:py-20">{experience.education?.length ? <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sky-800">Education</p><div className="mt-5"><DetailList items={experience.education} /></div></div> : null}{experience.certifications?.length ? <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sky-800">Certifications</p><div className="mt-5"><DetailList items={experience.certifications} /></div></div> : null}{experience.publications?.length ? <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sky-800">Publications</p><div className="mt-5"><DetailList items={experience.publications} /></div></div> : null}</section> : null}
    <Section id="contact" label="04 / get in touch" title="Let’s build something useful."><div className="flex flex-wrap items-center gap-x-6 gap-y-3 text-lg">{contactLinks.map((link) => <a className="font-semibold text-sky-800 underline decoration-sky-300 underline-offset-4 transition hover:text-stone-950" href={link.href} key={link.label} rel="noreferrer" target="_blank">{link.label}</a>)}{contact?.phone_number ? <a className="font-semibold text-sky-800 underline decoration-sky-300 underline-offset-4 transition hover:text-stone-950" href={`tel:${contact.phone_number}`}>{contact.phone_number}</a> : null}</div></Section><footer className="border-t border-stone-300 py-8 text-sm text-stone-500">© {new Date().getFullYear()} {fullName || "Portfolio"}</footer></div></main>;
}
